[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install',
  'cd packages/backend && npx prisma generate'
]

[phases.build]
cmds = ['npm run build -w packages/backend']

[start]
cmd = 'cd packages/backend && npm start'
