[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install --workspace=packages/shared',
  'npm install --workspace=packages/backend',
  'cd packages/backend && npx prisma generate'
]

[phases.build]
cmds = ['cd packages/backend && npm run build']

[start]
cmd = 'cd packages/backend && npm start'
