[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd ../..",
  "npm ci",
  "npm run build -w packages/shared"
]

[phases.build]
cmds = [
  "cd packages/backend",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "node packages/backend/dist/index.js"
